<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Moneybox.Payments.FamilyPayments</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LaunchDarkly.ServerSdk" Version="8.6.0" />
  </ItemGroup>

  <!-- Exclude test files from the main project -->
  <ItemGroup>
    <Compile Remove="Tests\**" />
  </ItemGroup>

</Project>
